apiVersion: v1
kind: Service
metadata:
  name: flask-service
  namespace: flask-redis-namespace
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 5000
  selector:
    app: flask-app